[package]
name = "crossword"
license = "AGPL-3.0-only"
description = "Library for crossword puzzles including .puz file parsing"
readme = "README.md"
version.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
encoding = "0.2"
